const $=selector=>document.querySelector(selector);
  const game=$('#game'),player=$('#player'),clawHead=$('.claw-head'),exitDoor=$('.exit'),message=$('#message'),won=$('#won'),timer=$('#timer'),best=$('#best'),escapes=$('#escapes'),deaths=$('#deaths'),resultStats=$('#resultStats'),resultBadge=$('#resultBadge'),restart=$('#restart'),again=$('#again');
  const bestKey='nestEscapeClawChaosBest',escapesKey='nestEscapeClawChaosEscapes';
  const state={x:7,y:0,vx:0,vy:0,grounded:true,active:true,keys:new Set(),last:0,elapsed:0,clawed:0,escapes:readNumber(escapesKey),best:readNumber(bestKey),hintLevel:0};
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  function readNumber(key){try{const value=Number(localStorage.getItem(key));return Number.isFinite(value)&&value>0?value:0}catch{return 0}}
  function saveNumber(key,value){try{localStorage.setItem(key,String(value))}catch{}}
  function setMessage(text,type=''){message.textContent=text;message.className='message '+type;}
  function updateStats(){const time=state.elapsed.toFixed(1),record=state.best?state.best.toFixed(1)+'s':'--';timer.textContent=time;best.textContent=record;escapes.textContent=state.escapes;deaths.textContent=state.clawed;}
  function render(){player.style.left=state.x+'%';player.style.bottom=(21+state.y)+'%';player.classList.toggle('airborne',!state.grounded);player.classList.toggle('facing-left',state.vx<-.4);$('.shadow').style.transform='scaleX('+(state.grounded?1:Math.max(.45,1-state.y/95))+')';$('.shadow').style.opacity=state.grounded?'.75':'.38';updateStats();}
  function box(el){return el.getBoundingClientRect()}
  function hits(a,b,pad=7){const A=box(a),B=box(b);return A.left<B.right-pad&&A.right>B.left+pad&&A.top<B.bottom-pad&&A.bottom>B.top+pad}
  function clearInput(){state.keys.clear();state.vx=0;}
  function reset(text='Fresh attempt. Wait for the claw, then take the gap.',returnFocus=true){Object.assign(state,{x:7,y:0,vx:0,vy:0,grounded:true,active:true,elapsed:0,last:performance.now()});clearInput();won.classList.remove('show');setMessage(text,'tip');render();if(returnFocus)restart.focus({preventScroll:true});}
  function land(){player.classList.remove('landing');void player.offsetWidth;player.classList.add('landing');setTimeout(()=>player.classList.remove('landing'),220);}
  function lose(){if(!state.active)return;state.active=false;state.clawed++;clearInput();game.classList.remove('shake');void game.offsetWidth;game.classList.add('shake');const tips=['CLAWED. The cable is harmless; wait for the head to swing away.','CLAWED. Try a shorter dash after the claw passes right.','CLAWED. Jump late if you need a little extra clearance.'];setMessage(tips[Math.min(state.hintLevel++,tips.length-1)],'danger');render();player.animate([{filter:'brightness(1)'},{filter:'brightness(2.3) saturate(.2)'},{filter:'brightness(1)'}],{duration:280});}
  function jump(){if(state.active&&state.grounded){state.vy=45;state.grounded=false;setMessage('Nice jump. Keep your eyes on the claw.');}}
  function medal(){if(state.elapsed<4)return'SPEEDY ESCAPE';if(state.clawed===0)return'CLEAN DASH';return'PERSISTENCE PAYS';}
  function celebrate(){for(let i=0;i<22;i++){const piece=document.createElement('i');piece.className='confetti';piece.style.left=(35+Math.random()*30)+'%';piece.style.top='18%';piece.style.background=['#ffd452','#5cf1df','#ff619f','#fff7dc'][i%4];piece.style.setProperty('--x',(-180+Math.random()*360)+'px');game.append(piece);setTimeout(()=>piece.remove(),1200);}}
  function win(){if(!state.active)return;state.active=false;clearInput();const newBest=!state.best||state.elapsed<state.best;if(newBest){state.best=state.elapsed;saveNumber(bestKey,state.best);}state.escapes++;saveNumber(escapesKey,state.escapes);resultBadge.textContent=medal()+(newBest?' · NEW BEST':'');render();setMessage(newBest?'Exit found! New best time.':'Exit found!','success');won.classList.add('show');celebrate();again.focus({preventScroll:true});}
  function update(time){const dt=Math.min((time-state.last)/1000,.035)||0;state.last=time;if(state.active&&!document.hidden){state.elapsed+=dt;const direction=(state.keys.has('left')?-1:0)+(state.keys.has('right')?1:0);state.vx+=direction*78*dt;state.vx*=Math.pow(.00008,dt);state.x=clamp(state.x+state.vx*dt,2,92);if(!state.grounded){state.vy-=110*dt;state.y+=state.vy*dt;if(state.y<=0){state.y=0;state.vy=0;state.grounded=true;land();}}render();if(hits(player,clawHead,5))lose();else if(hits(player,exitDoor,14))win();}requestAnimationFrame(update);}
  function keyName(key){return key==='ArrowLeft'||key==='a'||key==='A'?'left':key==='ArrowRight'||key==='d'||key==='D'?'right':null;}
  addEventListener('keydown',event=>{const move=keyName(event.key);if(move){event.preventDefault();state.keys.add(move);}if(['ArrowUp','w','W',' '].includes(event.key)){event.preventDefault();jump();}if(event.key==='r'||event.key==='R')reset();if(event.key==='Escape'&&won.classList.contains('show'))reset();});
  addEventListener('keyup',event=>{const move=keyName(event.key);if(move)state.keys.delete(move);});
  addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInput();state.last=performance.now();});
  document.querySelectorAll('[data-move]').forEach(button=>{const move=Number(button.dataset.move)>0?'right':'left';button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);state.keys.add(move);});['pointerup','pointercancel','lostpointercapture','pointerleave'].forEach(type=>button.addEventListener(type,()=>state.keys.delete(move)));});
  $('#jump').addEventListener('pointerdown',event=>{event.preventDefault();jump();});restart.addEventListener('click',()=>reset());again.addEventListener('click',()=>reset());
  reset('Watch the claw swing, then dash right for the exit.',false);requestAnimationFrame(update);