import * as THREE from 'https://unpkg.com/three@0.161.0/build/three.module.js';

const canvas=document.querySelector('#scene'), message=document.querySelector('#message'), timeEl=document.querySelector('#time'), bestEl=document.querySelector('#best'), clawedEl=document.querySelector('#clawed'), won=document.querySelector('#won'), result=document.querySelector('#result'), badge=document.querySelector('#badge');
const restart=document.querySelector('#restart'),again=document.querySelector('#again');
const BEST='nestEscape3DBest';
const state={x:-8,y:0,vx:0,vy:0,grounded:true,active:true,keys:new Set(),start:performance.now(),elapsed:0,clawed:0,best:readBest(),last:performance.now()};
function readBest(){try{return Number(localStorage.getItem(BEST))||0}catch{return 0}}function saveBest(v){try{localStorage.setItem(BEST,v)}catch{}}
function note(text,type=''){message.textContent=text;message.className=type}function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x10122d);scene.fog=new THREE.Fog(0x10122d,20,49);
const camera=new THREE.PerspectiveCamera(49,innerWidth/innerHeight,.1,100);camera.position.set(0,8.2,21);camera.lookAt(0,3,0);
const hemi=new THREE.HemisphereLight(0xaca7ff,0x1a193e,2.3);scene.add(hemi);const key=new THREE.DirectionalLight(0xffe8bd,3.2);key.position.set(-8,14,12);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);const pink=new THREE.PointLight(0xff4ea0,24,16,2);pink.position.set(11,6,4);scene.add(pink);const cyan=new THREE.PointLight(0x5cf1df,18,14,2);cyan.position.set(-10,5,4);scene.add(cyan);
function mat(color,rough=.7){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.08,flatShading:true})}function cube(w,h,d,color,x,y,z,group=scene){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;group.add(m);return m}function glow(color,intensity,dist,x,y,z){const l=new THREE.PointLight(color,intensity,dist,2);l.position.set(x,y,z);scene.add(l);return l}
// Room
cube(25,.6,9,0x292760,0,-.3,0);cube(25,12,.4,0x252253,0,5.7,-3.9);cube(.5,12,9,0x302b66,-12.2,5.7,0);cube(.5,12,9,0x302b66,12.2,5.7,0);
for(let x=-11;x<12;x+=2){cube(.055,.08,8.5,0x48438f,x,.04,0)}for(let z=-3;z<5;z+=2){cube(24,.08,.055,0x48438f,0,.05,z)}
for(let x=-10;x<=10;x+=5){const p=cube(2.4,5.8,.35,0x35316f,x,3,-3.66);const inset=cube(1.7,4.8,.04,0x4e4991,x,3,-3.45);inset.material.emissive=new THREE.Color(0x1a1642)}
// low poly arcade machine
const machine=new THREE.Group();scene.add(machine);machine.position.set(-7.9,0,-.45);cube(3.4,5.2,2.1,0x7651d6,0,2.6,0,machine);cube(3.65,.35,2.28,0xff8cbe,0,5.32,0,machine);cube(3.65,.35,2.28,0xff8cbe,0,.22,0,machine);cube(.28,5.3,2.28,0xff8cbe,-1.8,2.7,0,machine);cube(.28,5.3,2.28,0xff8cbe,1.8,2.7,0,machine);const glass=cube(2.85,2.65,.08,0x2c77d5,0,2.7,1.08,machine);glass.material.transparent=true;glass.material.opacity=.55;glass.material.emissive=new THREE.Color(0x1f5fca);cube(2.8,.55,.18,0x202267,0,4.55,1.16,machine);for(const [x,c] of [[-.85,0xffd452],[0,0xff619f],[.85,0x5cf1df]]){const prize=new THREE.Mesh(new THREE.IcosahedronGeometry(.36,1),mat(c));prize.position.set(x,1.35,1.13);machine.add(prize)}glow(0x5cf1df,8,7,-7.9,3,2);
// EXIT door
const exit=new THREE.Group();scene.add(exit);exit.position.set(8.5,0,-.2);cube(3.4,5.7,.5,0xb841ac,0,2.85,0,exit);cube(3.72,.32,.66,0xffd452,0,5.72,0,exit);cube(3.72,.32,.66,0xffd452,0,.18,0,exit);cube(.3,5.8,.66,0xffd452,-1.85,2.9,0,exit);cube(.3,5.8,.66,0xffd452,1.85,2.9,0,exit);const sign=cube(2.35,.62,.08,0xff619f,0,4.65,.31,exit);sign.material.emissive=new THREE.Color(0xff276e);const exitLight=glow(0xff4ea0,19,11,8.5,3,2);
// player
const player=new THREE.Group();scene.add(player);const shirt=mat(0x5cf1df),skin=mat(0xffc89f),dark=mat(0x10122d);const body=new THREE.Mesh(new THREE.CylinderGeometry(.44,.55,.8,5),shirt);body.position.y=1.0;body.castShadow=true;player.add(body);const head=new THREE.Mesh(new THREE.IcosahedronGeometry(.52,2),skin);head.position.y=1.88;head.castShadow=true;player.add(head);const eye=new THREE.Mesh(new THREE.SphereGeometry(.065,8,8),dark);eye.position.set(.27,1.96,.43);player.add(eye);const legMat=mat(0x373274);for(const x of [-.22,.22]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.22,.55,.25),legMat);leg.position.set(x,.35,0);leg.castShadow=true;player.add(leg)}const playerLight=glow(0x5cf1df,2.8,5,-8,2,2);
// claw rail and crane
cube(8,.18,.38,0xc4fff9,0,8,-.25);const clawRig=new THREE.Group();scene.add(clawRig);clawRig.position.set(0,8,-.1);const cable=cube(.11,5.2,.11,0xffe968,0,-2.6,0,clawRig);const head=new THREE.Mesh(new THREE.CylinderGeometry(.42,.58,.45,6),mat(0xe8b63a));head.position.y=-5.22;head.castShadow=true;clawRig.add(head);for(const x of [-.4,.4]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.12,.55,.12),mat(0xffe968));arm.position.set(x,-5.55,0);arm.rotation.z=x>0?-.45:.45;clawRig.add(arm)}const warning=new THREE.Mesh(new THREE.RingGeometry(.65,1.15,24),new THREE.MeshBasicMaterial({color:0xffd452,transparent:true,opacity:.58,side:THREE.DoubleSide}));warning.rotation.x=-Math.PI/2;warning.position.y=.035;scene.add(warning);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function reset(text='Fresh run. Time your dash past the claw.'){Object.assign(state,{x:-8,y:0,vx:0,vy:0,grounded:true,active:true,elapsed:0,start:performance.now(),last:performance.now()});state.keys.clear();won.classList.remove('show');note(text);restart.focus({preventScroll:true});}
function lose(){if(!state.active)return;state.active=false;state.clawed++;note('CLAWED. Wait until the claw swings away, then dash.','danger');canvas.animate([{filter:'brightness(1)'},{filter:'brightness(1.7) saturate(.3)'},{filter:'brightness(1)'}],{duration:260});}
function win(){if(!state.active)return;state.active=false;const newBest=!state.best||state.elapsed<state.best;if(newBest){state.best=state.elapsed;saveBest(state.best)}badge.textContent=(state.elapsed<4?'SPEEDY 3D ESCAPE':'LOW-POLY LEGEND')+(newBest?' · NEW BEST':'');result.textContent=`Time: ${state.elapsed.toFixed(1)}s · Clawed: ${state.clawed}`;won.classList.add('show');again.focus({preventScroll:true});note('You escaped the 3D claw machine!','good');}
function jump(){if(state.active&&state.grounded){state.grounded=false;state.vy=9.7;note('Nice jump. Keep the exit in sight.')}}
function updateHud(){timeEl.textContent=state.elapsed.toFixed(1);bestEl.textContent=state.best?state.best.toFixed(1)+'s':'--';clawedEl.textContent=state.clawed}
function loop(now){const dt=Math.min((now-state.last)/1000,.035);state.last=now;const swing=Math.sin(now*.0019)*3.1;clawRig.position.x=swing;clawRig.rotation.z=Math.sin(now*.0019)*.20;warning.position.x=swing;warning.material.opacity=.32+Math.sin(now*.004)*.18;exitLight.intensity=15+Math.sin(now*.005)*5;if(state.active&&!document.hidden){state.elapsed+=dt;const dir=(state.keys.has('left')?-1:0)+(state.keys.has('right')?1:0);state.vx+=dir*26*dt;state.vx*=Math.pow(.00005,dt);state.x=clamp(state.x+state.vx*dt,-10.6,10.3);if(!state.grounded){state.vy-=24*dt;state.y+=state.vy*dt;if(state.y<=0){state.y=0;state.vy=0;state.grounded=true}}player.position.set(state.x,state.y,0);player.rotation.y=state.vx<-.2?Math.PI:0;player.rotation.z=state.grounded?0:Math.sin(now*.02)*.13;playerLight.position.set(state.x,state.y+2,2);const clawX=swing,clawY=3.95;if(Math.abs(state.x-clawX)<.78&&state.y<1.25)lose();if(state.x>7.2&&state.y<1.35)win();updateHud()}renderer.render(scene,camera);requestAnimationFrame(loop)}
function moveKey(k){return k==='ArrowLeft'||k==='a'||k==='A'?'left':k==='ArrowRight'||k==='d'||k==='D'?'right':null}addEventListener('keydown',e=>{const k=moveKey(e.key);if(k){e.preventDefault();state.keys.add(k)}if(['ArrowUp','w','W',' '].includes(e.key)){e.preventDefault();jump()}if(e.key==='r'||e.key==='R')reset();if(e.key==='Escape'&&won.classList.contains('show'))reset()});addEventListener('keyup',e=>{const k=moveKey(e.key);if(k)state.keys.delete(k)});addEventListener('blur',()=>state.keys.clear());document.addEventListener('visibilitychange',()=>{state.keys.clear();state.last=performance.now()});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);state.keys.add(k)});for(const type of ['pointerup','pointerleave','pointercancel','lostpointercapture'])b.addEventListener(type,()=>state.keys.delete(k))});document.querySelector('#jump').addEventListener('pointerdown',e=>{e.preventDefault();jump()});restart.onclick=()=>reset();again.onclick=()=>reset();reset('Welcome to 3D Claw Chaos. Wait for the claw, then run right.');requestAnimationFrame(loop);
