import * as THREE from 'https://unpkg.com/three@0.161.0/build/three.module.js';

const canvas=document.querySelector('#scene');
const intro=document.querySelector('#intro'),won=document.querySelector('#won'),start=document.querySelector('#start'),again=document.querySelector('#again'),restart=document.querySelector('#restart');
const speech=document.querySelector('#speech'),coresEl=document.querySelector('#cores'),timeEl=document.querySelector('#time'),bestEl=document.querySelector('#best'),result=document.querySelector('#result'),objective=document.querySelector('#objective');
const BEST='nestEscapeRoom01Best3D';
function bestRead(){try{return Number(localStorage.getItem(BEST))||0}catch{return 0}}function bestSave(v){try{localStorage.setItem(BEST,v)}catch{}}
function say(who,text,kind=''){speech.innerHTML=`<span class="speaker">${who}</span><br>${text}`;speech.className=kind}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
const state={active:false,last:performance.now(),started:0,elapsed:0,best:bestRead(),keys:new Set(),cores:0,deaths:0,stage:0,shake:0,flash:0,clawTarget:0};
const P={x:-9,y:0,vx:0,vy:0,facing:1,ground:true,coyote:0,jumpBuffer:0,dash:0,dashCD:0,run:0,land:0,hit:0};

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x080a1d);scene.fog=new THREE.Fog(0x080a1d,22,49);
const camera=new THREE.PerspectiveCamera(47,innerWidth/innerHeight,.1,100);camera.position.set(0,7.5,21.6);camera.lookAt(0,3.1,0);
scene.add(new THREE.HemisphereLight(0x9aaaff,0x17112c,1.75));const key=new THREE.DirectionalLight(0xffe2bf,2.35);key.position.set(-8,14,10);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);
function standard(color,rough=.72){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.08,flatShading:true})}function box(w,h,d,mat,x,y,z,into=scene){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;into.add(m);return m}function glow(color,intensity,distance,x,y,z){const l=new THREE.PointLight(color,intensity,distance,2);l.position.set(x,y,z);scene.add(l);return l}
function canvasTexture(draw,rx=1,ry=1){const c=document.createElement('canvas');c.width=c.height=192;const g=c.getContext('2d');draw(g);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(rx,ry);return t}
const floorTex=canvasTexture(g=>{g.fillStyle='#232642';g.fillRect(0,0,192,192);for(let y=0;y<192;y+=48)for(let x=0;x<192;x+=48){g.fillStyle=(x+y)/48%2?'#292c4e':'#20223d';g.fillRect(x+2,y+2,44,44);g.strokeStyle='#5b5f8c';g.globalAlpha=.45;g.strokeRect(x+2,y+2,44,44);g.globalAlpha=1}},6,3);
const wallTex=canvasTexture(g=>{g.fillStyle='#36365c';g.fillRect(0,0,192,192);for(let y=0;y<192;y+=39){g.fillStyle='#29294a';g.fillRect(0,y,192,5);g.fillStyle='#56577f';g.globalAlpha=.5;g.fillRect(0,y+5,192,2);g.globalAlpha=1}},7,3);
function label(text,color,w=2.4){const c=document.createElement('canvas');c.width=512;c.height=128;const g=c.getContext('2d');g.fillStyle='#11132c';g.fillRect(0,0,512,128);g.strokeStyle='#ffffff77';g.lineWidth=8;g.strokeRect(8,8,496,112);g.fillStyle=color;g.font='900 69px Trebuchet MS';g.textAlign='center';g.textBaseline='middle';g.fillText(text,256,68);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return new THREE.Mesh(new THREE.PlaneGeometry(w,w/4),new THREE.MeshBasicMaterial({map:t,transparent:true}))}

// A real, readable low-poly arcade interior.
box(25,.5,9,new THREE.MeshStandardMaterial({map:floorTex,roughness:.8}),0,-.25,0);box(25,10.8,.35,new THREE.MeshStandardMaterial({map:wallTex,roughness:.8}),0,5.2,-4.05);box(25,.42,9,standard(0x292b43),0,10.05,0);box(.42,10.8,9,standard(0x626579),-12.25,5.2,0);box(.42,10.8,9,standard(0x626579),12.25,5.2,0);
for(const x of [-10,-5,0,5,10]){box(.5,10,.7,standard(0x74778b),x,5,.18);box(.76,.27,.92,standard(0x252743),x,9.65,.18)}for(const z of [-2.6,2.6])box(23.6,.22,.2,standard(0x8c91ac),0,9.32,z);for(const x of [-8,-3.5,3.5,8]){box(3.25,4.35,.08,standard(0x14224a),x,5.8,-3.77);box(.14,4.3,.11,standard(0x7782aa),x,5.8,-3.64);box(3.15,.14,.11,standard(0x7782aa),x,5.8,-3.64);for(let i=0;i<6;i++)box(.08,.08,.02,standard(i%2?0x5cf1df:0xffd452),x-1.1+(i%3)*1.1,4.7+Math.floor(i/3)*1.6,-3.61);glow(0x4f75cf,1.25,6,x,5.5,-2.7)}
for(const x of [-8,-2,4,9]){const lamp=box(1.55,.1,.42,standard(0xd8edff),x,9.05,1.2);lamp.material.emissive=new THREE.Color(0x84baff);lamp.material.emissiveIntensity=1.4;glow(0xb3d7ff,2.1,7,x,8.6,1.2)}
const sign=label('ARCADE FLOOR',0x5cf1df,2.8);sign.position.set(-4.2,7.55,-3.55);scene.add(sign);const sign2=label('NIGHT SHIFT EXIT →',0xffd452,3.4);sign2.position.set(4.4,7.55,-3.55);scene.add(sign2);
function cabinet(x,z,color,name){const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);box(1.42,2.55,.82,standard(0x283052),0,1.28,0,g);box(1.58,.22,.95,standard(color),0,2.6,0,g);const screen=box(1,.82,.025,standard(0x0a1838),0,1.78,.43,g);screen.material.emissive=new THREE.Color(color);screen.material.emissiveIntensity=.72;const l=label(name,color,1.02);l.position.set(0,2.2,.48);g.add(l);box(.62,.09,.25,standard(0x141a32),0,.72,.46,g)}cabinet(-4,-2.75,0x5cf1df,'PIXEL');cabinet(-2.18,-2.78,0xff619f,'BEAT');cabinet(1.9,-2.78,0xffd452,'RACE');
for(const x of [-10.6,10.6]){box(.65,.85,.65,standard(0x344267),x,.43,2.9);box(.76,.12,.76,standard(0x1c2540),x,.9,2.9)}

// Machine sits in the room; crane actually runs a search → target → drop → grab → lift cycle.
const machine=new THREE.Group();machine.position.set(-8,0,-.32);scene.add(machine);box(3.25,5.1,2.1,standard(0x574faf),0,2.55,0,machine);box(3.58,.3,2.3,standard(0xff8cbe),0,5.26,0,machine);box(3.58,.3,2.3,standard(0xff8cbe),0,.2,0,machine);for(const x of [-1.63,1.63])box(.28,5.1,2.3,standard(0xff8cbe),x,2.65,0,machine);const glass=box(2.72,2.5,.06,standard(0x206fc0),0,2.7,1.08,machine);glass.material.transparent=true;glass.material.opacity=.34;glass.material.emissive=new THREE.Color(0x146dcc);const mt=label('CLAW CHAOS',0xff9ec7,2.5);mt.position.set(0,4.55,1.25);machine.add(mt);for(const [x,c] of [[-.82,0xffd452],[0,0xff619f],[.82,0x5cf1df]]){const prize=new THREE.Mesh(new THREE.IcosahedronGeometry(.31,1),standard(c));prize.position.set(x,1.28,1.15);prize.castShadow=true;machine.add(prize)}glow(0x5cf1df,7,7,-8,3,1.7);
const exit=new THREE.Group();exit.position.set(8.85,0,-.15);scene.add(exit);box(3.4,5.7,.5,standard(0x813d9d),0,2.85,0,exit);box(3.75,.3,.65,standard(0xffd452),0,5.7,0,exit);for(const x of [-1.85,1.85])box(.28,5.8,.65,standard(0xffd452),x,2.9,0,exit);const et=label('LOCKED',0xffd452,2.05);et.position.set(0,4.6,.29);exit.add(et);state.exitSign=et;const exitLamp=glow(0xff4ea0,13,10,8.85,3,1.8);

const rail=box(17,.2,.36,standard(0xc8ffff),0,8,-.05);const trolley=new THREE.Group();scene.add(trolley);box(.82,.35,.7,standard(0x535983),0,0,0,trolley);const cable=box(.09,1,.09,standard(0xffe968),0,-.5,0,trolley);const claw=new THREE.Group();claw.position.y=-1;trolley.add(claw);const clawTop=new THREE.Mesh(new THREE.CylinderGeometry(.43,.56,.44,6),standard(0xe8b63a));clawTop.castShadow=true;claw.add(clawTop);const arms=[];for(const side of [-1,1]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.13,.72,.14),standard(0xffe968));arm.position.set(side*.33,-.45,0);arm.castShadow=true;claw.add(arm);arms.push(arm)}const warning=new THREE.Mesh(new THREE.RingGeometry(.68,1.05,20),new THREE.MeshBasicMaterial({color:0xffd452,transparent:true,opacity:.5,side:THREE.DoubleSide}));warning.rotation.x=-Math.PI/2;warning.position.y=.028;scene.add(warning);

// Animated player: body, legs, arms, head and a small glow. Low polygon count, clear read.
const player=new THREE.Group();scene.add(player);const body= new THREE.Mesh(new THREE.CylinderGeometry(.42,.54,.84,5),standard(0x5cf1df));body.position.y=1.02;body.castShadow=true;player.add(body);const head=new THREE.Mesh(new THREE.IcosahedronGeometry(.52,2),standard(0xffc89f));head.position.y=1.88;head.castShadow=true;player.add(head);const eye=new THREE.Mesh(new THREE.SphereGeometry(.06,8,8),standard(0x10122d));eye.position.set(.29,1.97,.42);player.add(eye);const legs=[],armsP=[];for(const x of [-.22,.22]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.2,.58,.24),standard(0x373274));leg.position.set(x,.34,0);leg.castShadow=true;player.add(leg);legs.push(leg);const arm=new THREE.Mesh(new THREE.BoxGeometry(.16,.58,.18),standard(0xffc89f));arm.position.set(x*2.4,1.1,0);arm.castShadow=true;player.add(arm);armsP.push(arm)}const playerGlow=glow(0x5cf1df,2.3,5,-9,2,1.8);

const cores=[{x:-3.9,z:1.2,found:false},{x:.15,z:-.2,found:false},{x:5.05,z:1.45,found:false}];for(const c of cores){const g=new THREE.Group();const shell=new THREE.Mesh(new THREE.OctahedronGeometry(.34,1),standard(0xffd452));shell.castShadow=true;g.add(shell);const halo=new THREE.Mesh(new THREE.RingGeometry(.45,.6,12),new THREE.MeshBasicMaterial({color:0xffe968,transparent:true,opacity:.55,side:THREE.DoubleSide}));halo.rotation.x=-Math.PI/2;halo.position.y=-.36;g.add(halo);g.position.set(c.x,.78,c.z);scene.add(g);c.mesh=g;c.light=glow(0xffd452,3.5,4,c.x,1.1,c.z)}

function setExitLabel(text,color){if(state.exitSign)exit.remove(state.exitSign);const sign=label(text,color,2.15);sign.position.set(0,4.6,.3);exit.add(sign);state.exitSign=sign}function reset(text='Find the three stolen power cores.'){Object.assign(P,{x:-9,y:0,vx:0,vy:0,facing:1,ground:true,coyote:0,jumpBuffer:0,dash:0,dashCD:0,run:0,land:0,hit:0});cores.forEach(c=>{c.found=false;c.mesh.visible=true;c.light.visible=true});Object.assign(state,{active:true,started:performance.now(),elapsed:0,cores:0,deaths:0,stage:0,shake:0,flash:0,last:performance.now()});state.keys.clear();exitLamp.color.set(0xff4ea0);setExitLabel('LOCKED',0xffd452);won.classList.add('hidden');objective.innerHTML='Objective: recover <b>3 stolen power cores</b> to unlock the Night Shift Exit.';say('NEST AI',text);updateHud()}
function updateHud(){coresEl.textContent=state.cores+'/3';timeEl.textContent=state.elapsed.toFixed(1);bestEl.textContent=state.best?state.best.toFixed(1)+'s':'--'}
function jump(){P.jumpBuffer=.14}function dash(){if(state.active&&P.dashCD<=0){P.dash=.18;P.dashCD=.66;P.vx=P.facing*17;P.vy*=.3;say('YOU','Dash! That is the correct reaction to a giant claw.','good')}}
function die(){if(P.hit>0||!state.active)return;P.hit=.55;P.vx=-P.facing*8;P.vy=7.2;state.deaths++;state.shake=.3;state.flash=.18;say('NEST AI','GRAB DETECTED. Cores remain collected. Try reading the claw cycle.','danger')}
function collect(c){c.found=true;c.mesh.visible=false;c.light.visible=false;state.cores++;state.flash=.1;if(state.cores===1)say('NEST AI','Core one restored. The claw has entered active patrol.');else if(state.cores===2)say('NEST AI','Core two restored. One more. The exit is beginning to listen.');else{objective.innerHTML='Objective: <b>the Night Shift Exit is open</b> — reach it.';setExitLabel('EXIT OPEN',0x5cf1df);exitLamp.color.set(0x5cf1df);say('NEST AI','All cores restored. Exit unlocked. Get out now.','good')}}
function win(){if(!state.active||state.cores<3)return;state.active=false;const newBest=!state.best||state.elapsed<state.best;if(newBest){state.best=state.elapsed;bestSave(state.best)}result.textContent=`You restored the arcade grid, outplayed Claw Chaos, and reached the exit in ${state.elapsed.toFixed(1)}s. Claw grabs: ${state.deaths}.${newBest?' New best.':''}`;won.classList.remove('hidden');say('NEST AI','Room 01 clear. The lobby doors are opening. Probably.','good')}
function clawCycle(now){const cycle=(now*.00012)%1;let x,y,phase;if(cycle<.34){phase='patrol';x=-5.7+cycle/.34*11.4;y=6.35}else if(cycle<.50){phase='target';state.clawTarget=clamp(P.x,-4.6,5.7);x=state.clawTarget;y=6.35}else if(cycle<.70){phase='drop';x=state.clawTarget;y=6.35-(cycle-.50)/.20*4.85}else if(cycle<.80){phase='grab';x=state.clawTarget;y=1.5}else{phase='lift';x=state.clawTarget;y=1.5+(cycle-.80)/.20*4.85}trolley.position.set(x,7.9,0);cable.scale.y=(7.9-y);cable.position.y=-(7.9-y)/2;claw.position.y=-(7.9-y);const closing=phase==='grab'||phase==='lift';arms.forEach((arm,i)=>{arm.rotation.z=(i?1:-1)*(closing?.95:.38)});warning.position.set(x,.032,0);warning.material.opacity=(phase==='drop'||phase==='grab')?.72:.22;return{x,y:Math.max(0,y-1.05),phase}}
function updatePlayer(dt,now){P.jumpBuffer-=dt;P.dash=Math.max(0,P.dash-dt);P.dashCD=Math.max(0,P.dashCD-dt);P.hit=Math.max(0,P.hit-dt);P.land=Math.max(0,P.land-dt);state.shake=Math.max(0,state.shake-dt);state.flash=Math.max(0,state.flash-dt);const dir=(state.keys.has('left')?-1:0)+(state.keys.has('right')?1:0);if(dir){P.facing=dir;P.vx+=dir*(P.dash?0:30)*dt;P.run+=dt*14}else P.run+=dt*Math.abs(P.vx)*.04;const max=P.dash?17:5.6;P.vx=clamp(P.vx,-max,max);P.vx*=Math.pow(P.ground?.0007:.035,dt);if(P.jumpBuffer>0&&(P.ground||P.coyote>0)){P.vy=10.1;P.ground=false;P.coyote=0;P.jumpBuffer=0;say('YOU','Jumping over industrial machinery: not in the manual, somehow.')}if(!P.ground){P.vy-=27*dt;P.y+=P.vy*dt;if(P.y<=0){if(P.vy<-5)P.land=.13;P.y=0;P.vy=0;P.ground=true}}else P.coyote=.1;P.x=clamp(P.x+P.vx*dt,-10.5,10.35);player.position.set(P.x,P.y,0);player.rotation.y=P.facing<0?Math.PI:0;player.rotation.z=P.ground?0:Math.sin(now*.02)*.1;const swing=Math.sin(P.run)*.72*(P.ground?1:0);legs[0].rotation.x=swing;legs[1].rotation.x=-swing;armsP[0].rotation.x=-swing*.7;armsP[1].rotation.x=swing*.7;player.scale.set(P.land>0?1.1:1,P.ground?1:(1.08),P.land>0?1.1:1);player.visible=P.hit<=0||Math.sin(now*.04)>0;playerGlow.position.set(P.x,P.y+2,1.8)}
function loop(now){const dt=Math.min((now-state.last)/1000,.035);state.last=now;const clawState=clawCycle(now);if(state.active&&!document.hidden){state.elapsed=(now-state.started)/1000;updatePlayer(dt,now);for(const c of cores){if(!c.found&&Math.abs(P.x-c.x)<.72&&Math.abs(P.y)<1.1)collect(c);if(!c.found){c.mesh.rotation.y+=dt*2.6;c.mesh.position.y=.78+Math.sin(now*.004+c.x)*.13}}if(P.hit<=0&&clawState.phase==='grab'&&Math.abs(P.x-clawState.x)<.72&&P.y<1.15)die();if(P.x>7.45&&state.cores===3)win();updateHud()}const shake=state.shake?Math.sin(now*.09)*state.shake*1.4:0;camera.position.x=shake;camera.lookAt(shake*.1,3.1,0);renderer.render(scene,camera);requestAnimationFrame(loop)}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);function moveKey(k){return['ArrowLeft','a','A'].includes(k)?'left':['ArrowRight','d','D'].includes(k)?'right':null}addEventListener('keydown',e=>{const k=moveKey(e.key);if(k){e.preventDefault();state.keys.add(k)}if(['ArrowUp','w','W',' '].includes(e.key)){e.preventDefault();jump()}if(['Shift','x','X'].includes(e.key)){e.preventDefault();dash()}if(['r','R'].includes(e.key))reset()});addEventListener('keyup',e=>{const k=moveKey(e.key);if(k)state.keys.delete(k)});addEventListener('blur',()=>state.keys.clear());document.addEventListener('visibilitychange',()=>{state.keys.clear();state.last=performance.now()});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);state.keys.add(k)});for(const t of ['pointerup','pointerleave','pointercancel','lostpointercapture'])b.addEventListener(t,()=>state.keys.delete(k))});document.querySelector('#jump').addEventListener('pointerdown',e=>{e.preventDefault();jump()});document.querySelector('#dash').addEventListener('pointerdown',e=>{e.preventDefault();dash()});start.onclick=()=>{intro.classList.add('hidden');reset('The lock has engaged. Find the cores before the claw completes its first sweep.')};again.onclick=()=>reset();restart.onclick=()=>reset();resize();reset();requestAnimationFrame(loop);
