
"use strict";
const cv=document.querySelector("#game"),g=cv.getContext("2d");const count=document.querySelector("#count"),alertUI=document.querySelector("#alert"),message=document.querySelector("#message"),objective=document.querySelector("#objective"),intro=document.querySelector("#intro"),finish=document.querySelector("#finish"),summary=document.querySelector("#summary");
const W=1280,H=720,GROUND=612;let S=1,OX=0,OY=0,last=0;const K=new Set(),particles=[],rain=[],ART={roof:null,archive:null,escape:null,agent:null,poses:null};let artReady=false;
async function loadArt(name,parts){let raw="";for(let i=1;i<=parts;i++){const r=await fetch(`glass-art-${name}-${i}.txt`,{cache:"force-cache"});if(!r.ok)throw Error(name);raw+=await r.text()}return loadImage("data:image/webp;base64,"+raw)}
function loadImage(src){return new Promise((ok,no)=>{const im=new Image();im.onload=()=>ok(im);im.onerror=no;im.src=src})}
async function loadPoseSheet(){let raw="";for(let i=1;i<=7;i++){const r=await fetch(`glass-pose-${i}.txt`,{cache:"force-cache"});if(!r.ok)throw Error("poses");raw+=await r.text()}return loadImage("data:image/webp;base64,"+raw)}
Promise.all([loadArt("roof",9),loadArt("archive",6),loadArt("escape",8),loadArt("agent",4),loadPoseSheet()]).then(([roof,archive,escape,agent,poses])=>{Object.assign(ART,{roof,archive,escape,agent,poses});artReady=true;document.querySelector("#start").textContent="BEGIN OPERATION"}).catch(()=>{document.querySelector("#start").textContent="BEGIN OPERATION (ART LINK RETRY)"});
for(let n=0;n<180;n++)rain.push({x:Math.random()*3200,y:Math.random()*H,z:7+Math.random()*13,a:.16+Math.random()*.45});
let st={live:false,cam:0,chips:0,alert:0,checkpoint:0,shake:0,flash:0,alarmUntil:0,start:0,lastMsg:"",done:false};let p={x:100,y:552,w:30,h:48,vx:0,vy:0,face:1,ground:false,coy:0,buf:0,dash:0,cd:0,run:0,land:0};
const base=[ [0,612,430,180,"roof"],[175,530,126,22,"duct"],[361,451,125,22,"duct"],[538,542,103,22,"walk"],[705,461,131,22,"walk"],[892,530,120,22,"walk"], [1000,612,940,180,"archive"],[1080,520,142,22,"walk"],[1304,432,120,22,"walk"],[1518,512,110,22,"lift"],[1710,421,150,22,"walk"], [1940,612,1160,180,"roof"],[2030,522,145,22,"walk"],[2248,438,133,22,"walk"],[2460,510,112,22,"lift"],[2670,419,145,22,"walk"],[2885,522,135,22,"walk"]];const platforms=base.map((q,id)=>({x:q[0],y:q[1],w:q[2],h:q[3],kind:q[4],id,bx:q[0],by:q[1]}));
const collectibles=[{x:405,y:404,got:false},{x:1355,y:382,got:false},{x:2306,y:386,got:false}];const lasers=[{a:[485,581],b:[650,581],period:2.6,phase:0},{a:[1454,382],b:[1454,604],period:2.45,phase:.8},{a:[2368,480],b:[2555,480],period:2.15,phase:1.45}];const cameras=[{x:1172,y:348,base:.35,range:210,phase:0},{x:1880,y:356,base:2.72,range:195,phase:1.3},{x:2740,y:355,base:.15,range:210,phase:2.5}];const checkpoints=[{x:1030,room:1,label:"ARCHIVE RELAY"},{x:1980,room:2,label:"LOCKDOWN ROOF"}];const extraction={x:2980,y:544,open:false};
function size(){let r=Math.min(devicePixelRatio,1.5);cv.width=innerWidth*r;cv.height=innerHeight*r;S=Math.min(cv.width/W,cv.height/H);OX=(cv.width-W*S)/2;OY=(cv.height-H*S)/2}addEventListener("resize",size);size();function cl(v,a,b){return Math.max(a,Math.min(b,v))}function say(t){message.textContent=t;st.lastMsg=t}function hud(){count.textContent=st.chips+"/3";alertUI.textContent="● ".repeat(st.alert)+"○ ".repeat(3-st.alert)}function box(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}function on(l,t){return ((t/1000+l.phase)%l.period)<l.period*.67}function camA(q,t){return q.base+Math.sin(t/1000*1.45+q.phase)*.76}
function sparks(x,y,n=12,col="#54e7ff"){for(let i=0;i<n;i++){let a=Math.random()*6.28,v=45+Math.random()*155;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-60,life:.45+Math.random()*.35,max:.8,c:col,s:1+Math.random()*3})}}function reset(full=true){if(full){st.chips=0;st.alert=0;st.checkpoint=0;st.done=false;collectibles.forEach(q=>q.got=false);extraction.open=false}let q=st.checkpoint===0?{x:100,y:552}:st.checkpoint===1?{x:1045,y:552}:{x:1995,y:552};Object.assign(p,{...p,...q,vx:0,vy:0,ground:false,coy:0,buf:0,dash:0,cd:0,run:0});st.live=true;st.start=performance.now();say(st.checkpoint?"Checkpoint restored. Keep it clean.":"Roof access is clear. Move when the camera turns away.");objective.innerHTML=extraction.open?"OBJECTIVE · Get to the <b>extraction lift</b>.":"OBJECTIVE · Collect three access chips and cross the glassline to the extraction lift.";hud()}function jump(){p.buf=.15}function dash(){if(st.live&&p.cd<=0){p.dash=.18;p.cd=.68;p.vx=p.face*790;p.vy*=.25;sparks(p.x+p.w/2,p.y+30,9,"#a5f6ff");say("Dash burst. Keep momentum.")}}function fail(why){if(!st.live||st.flash)return;st.alert=Math.min(3,st.alert+1);st.flash=.33;st.shake=.35;st.alarmUntil=performance.now()+1500;sparks(p.x+p.w/2,p.y+25,25,"#ff4f68");say(why+" Rewinding to the last safe zone.");hud();setTimeout(()=>reset(false),470)}function grab(q){q.got=true;st.chips++;st.shake=.1;sparks(q.x,q.y,22,"#ffd369");if(st.chips===3){extraction.open=true;objective.innerHTML="OBJECTIVE · Get to the <b>extraction lift</b>.";say("All chips acquired. Extraction lift has opened.")}else say("Access chip secured. Two more signals ahead.");hud()}
function update(dt,t){if(!st.live)return;st.shake=Math.max(0,st.shake-dt);st.flash=Math.max(0,st.flash-dt);p.buf-=dt;p.cd=Math.max(0,p.cd-dt);p.dash=Math.max(0,p.dash-dt);p.land=Math.max(0,p.land-dt);platforms.forEach(q=>{if(q.kind==="lift")q.y=q.by+Math.sin(t/760+q.id)*66});let d=(K.has("right")?1:0)-(K.has("left")?1:0);if(d){p.face=d;p.vx+=d*(p.dash?0:2780)*dt;p.run+=dt*15}else p.run+=dt*Math.abs(p.vx)*.02;p.vx=cl(p.vx,-(p.dash?790:345),p.dash?790:345);p.vx*=Math.pow(p.ground?.0005:.045,dt);if(p.buf>0&&(p.ground||p.coy>0)){p.vy=-715;p.buffer=0;p.buf=0;p.ground=false;p.coy=0;sparks(p.x+p.w/2,p.y+p.h,5,"#c5f7ff")}let oldY=p.y;if(!p.ground)p.vy+=1940*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.x=cl(p.x,16,3050);p.ground=false;let ly=9999;for(const q of platforms)if(p.x+p.w>q.x+3&&p.x<q.x+q.w-3&&oldY+p.h<=q.y+8&&p.y+p.h>=q.y&&p.vy>=0)ly=Math.min(ly,q.y);if(ly<9999){if(p.vy>430){p.land=.14;sparks(p.x+p.w/2,ly,8,"#a4c6d2")}p.y=ly-p.h;p.vy=0;p.ground=true}else p.coy-=dt;if(p.y>748)fail("You lost the roof line.");for(const q of collectibles)if(!q.got&&box({x:p.x,y:p.y,w:p.w,h:p.h},{x:q.x-15,y:q.y-15,w:30,h:30}))grab(q);for(const q of checkpoints)if(p.x>q.x&&st.checkpoint<q.room){st.checkpoint=q.room;say("CHECKPOINT — "+q.label+".");sparks(p.x,p.y,15,"#54e7ff")}for(const q of lasers)if(on(q,t)&&laserHit(q))fail("Laser lattice triggered.");for(const q of cameras)if(seen(q,t)&&!p.dash)fail("Camera lock detected.");if(extraction.open&&p.x>2945){st.live=false;st.done=true;let sec=((t-st.start)/1000).toFixed(1);summary.textContent="You crossed the storm line, collected every access chip and reached extraction in "+sec+" seconds with "+st.alert+" alert marks.";finish.classList.remove("hidden")}let target=cl(p.x-W*.36,0,3100-W);st.cam+=(target-st.cam)*Math.min(1,dt*5);for(const r of rain){r.x-=r.z*dt*15;if(r.x<st.cam-40){r.x=st.cam+W+Math.random()*200;r.y=Math.random()*H}r.y+=r.z*dt*24;if(r.y>H){r.y=-20;r.x=st.cam+Math.random()*(W+150)}}for(let i=particles.length-1;i>=0;i--){let q=particles[i];q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=410*dt;if(q.life<=0)particles.splice(i,1)}hud()}
